"""create_final_tables

Revision ID: 506daf29636d
Revises: f5a5a6779738
Create Date: 2025-08-16 17:10:06.214116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '506daf29636d'
down_revision: Union[str, Sequence[str], None] = 'f5a5a6779738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('vector_table',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('text_chunk', sa.TEXT(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'history_table_id', ['id'])
    op.create_unique_constraint(None, 'history_table_uuid', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_table_uuid', type_='unique')
    op.drop_constraint(None, 'history_table_id', type_='unique')
    op.drop_table('vector_table')
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
